"""update column for monster and user

Revision ID: 0d09cca47848
Revises: 9e0636e96b9d
Create Date: 2024-02-26 02:41:47.849740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d09cca47848'
down_revision = '9e0636e96b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_monsters_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_monster_id_monsters', type_='foreignkey')
        batch_op.drop_column('monster_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monster_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_monster_id_monsters', 'monsters', ['monster_id'], ['id'])

    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_monsters_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
