"""Updated battles

Revision ID: 4dee5321a1d7
Revises: d9c549ba3bc9
Create Date: 2024-02-28 02:17:07.866323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dee5321a1d7'
down_revision = 'd9c549ba3bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.drop_column('user_turn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_turn', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
