"""initial

Revision ID: 9e0636e96b9d
Revises: 
Create Date: 2024-02-26 02:25:36.077468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0636e96b9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_turn', sa.Boolean(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_moves_monster_id_monsters')),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], name=op.f('fk_monster_moves_move_id_moves')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('computer', sa.Boolean(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_users_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], name=op.f('fk_battle_users_battle_id_battles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_battle_users_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle_users')
    op.drop_table('users')
    op.drop_table('monster_moves')
    op.drop_table('moves')
    op.drop_table('monsters')
    op.drop_table('battles')
    # ### end Alembic commands ###
